# Generated by Django 4.0.2 on 2022-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathh', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
    ]
